storage:
  type: minio

spring:
  profiles:
    group:
      test:
        - test
      prod:
        - prod
      dev:
        - dev
    default: local

  config:
    import: optional:file:domain-module.env[.properties]

  servlet:
    multipart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  jwt:
    private-key-pem: ${JWT_PRIVATE_KEY}
    public-key-pem: ${JWT_PUBLIC_KEY}
    access-expiration-time: 1800  # Access Token 만료 시간 (30분)
    refresh-expiration-time: 1209600  # Refresh Token 만료 시간 (14일)

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub