storage:
  type: s3

spring:
  aws:
    region:
      static: ${PROD_AWS_REGION}
    credentials:
      access-key: ${PROD_AWS_ACCESS_KEY}
      secret-key: ${PROD_AWS_SECRET_KEY}
    s3:
      bucket-name: ${PROD_S3_BUCKET_NAME}