storage:
  type: s3

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DOCKER_SPRING_DATASOURCE_URL}
    username: ${DEV_DOCKER_SPRING_DATASOURCE_USERNAME}
    password: ${DEV_DOCKER_SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      mode: always
      data-locations:
        - ${MYSQL_INIT_DML_SQL_PATH}

  # s3도입 후에는 삭제해야합니다.
  # 임의로 넣은 이유는 build가 되지 않아 임시조치로 넣었습니다.
  minio:
    endpoint: ${MINIO_ENDPOINT}
    bucket-name: ${MINIO_BUCKET_NAME}
    credentials:
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}

  aws:
    region:
      static: ${DEV_AWS_REGION}
    credentials:
      access-key: ${DEV_AWS_ACCESS_KEY}
      secret-key: ${DEV_AWS_SECRET_KEY}
    s3:
      bucket-name: ${DEV_S3_BUCKET_NAME}