storage:
  type: minio

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jwt:
    private-key-pem: ${LOCAL_JWT_PRIVATE_KEY}
    public-key-pem: ${LOCAL_JWT_PUBLIC_KEY}
    access-expiration-time: 1800  # Access Token 만료 시간 (30분)
    refresh-expiration-time: 1209600  # Refresh Token 만료 시간 (14일)

  sql:
    init:
      mode: always
      data-locations:
        - ${MYSQL_INIT_DML_SQL_PATH}

  minio:
    endpoint: ${MINIO_ENDPOINT}
    bucket-name: ${MINIO_BUCKET_NAME}
    credentials:
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}