dependencies {

	implementation project(':CultureSpot-Domain')

	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'

	// OAuth 2.0
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

	// swagger
	implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.2.0'
}

tasks.register("prepareKotlinBuildScriptModel"){}

bootJar {
	archiveFileName = 'api.jar'
}
