name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
      - 'feature/*'
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ▶️ Checkout Repository
        uses: actions/checkout@v4

      - name: ▶️ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: ▶️ Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: ▶️ Build with Gradle
        run: |
          ./gradlew clean 
          ./gradlew build --parallel -x test

      - name: ▶️ Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ▶️ Set lowercase repository name
        run: echo "REPO_NAME=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: ▶️ Build Docker image for batch module
        run: docker build -t ghcr.io/${{ env.REPO_NAME }}/batch:latest -f ./CultureSpot-Batch/Dockerfile .

      - name: ▶️ Push Docker image for batch module
        run: docker push ghcr.io/${{ env.REPO_NAME }}/batch:latest
